### ISSUE TITLE
Excellent work!

### ISSUE THREAD

**Issue by ghenry** [masashi-sutou/flutter_ios_voip_kit#1]
Just to say thanks for this. Will be trying out this week and next and looks better than:

https://pub.dev/packages/flutter_voip_push_notification

and

https://pub.dev/packages/flutter_call_kit

**Comment by masashi-sutou** [comment]
Thank you @ghenry. I also made an example that you can check the operation of flutter_ios_voip_kit using SkyWay. Please try it and tell me if you have any bugs. https://github.com/masashi-sutou/flutter_ios_webrtc_kit

**Comment by ghenry** [comment]
Will do!

PushKit and CallKit don't actually do any media do they? In the example I
noticed the green status bar and video camera icon appeared? I haven't
tested the example with two iPhones yet though, so I may be confused here.

**Comment by masashi-sutou** [comment]
@ghenry 

Sorry, I didn't understand what you meant by media. 

As you are aware, you need a VoIP notification server and two iPhones to get this example app to work perfectly. You can display the incoming call screen of CallKit on a single iPhone.

You can see the outgoing and incoming transitions in [this sample](https://github.com/masashi-sutou/flutter_ios_webrtc_kit), but without two iPhones and a VoIP server it wouldn't be fully functional(For example, incoming call operation while the iPhone is locked).

**Comment by ghenry** [comment]
Media is actual audio and video.

I'll do a video to explain tonight.

**Comment by ghenry** [comment]
On your screen shots you have talking. How is that possible here? Are you
handling the actual phone call too? I'll read your example more. I thought
the two kits just help integrate with the native iPhone UI.

**Comment by NarHakobyan** [comment]
@masashi-sutou hi, thanks for work)), can you please create an example with agora?

**Comment by ghenry** [comment]
Ah, I see you are doing the VoIP in the device natively for one to one calls. I thought this was just CallKit and PhoneKit, but you've listed https://developer.apple.com/documentation/callkit/making_and_receiving_voip_calls_with_callkit so you're doing a bit more than that.

**Comment by masashi-sutou** [comment]
@NarHakobyan 

For Agora, I recommend that you refer to the repository below.

- https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart
- https://github.com/AgoraIO-Community/Agora-Flutter-WebRTC-QuickStart
- https://github.com/AgoraIO-Usecase/Video-Calling
