### ISSUE TITLE
Unable to get voip Token sometimes

### ISSUE THREAD

**Issue by saurav0171** [masashi-sutou/flutter_ios_voip_kit#10]
Sometimes it fails to get Voip token from following method: 
FlutterIOSVoIPKit.instance.getVoIPToken(). Do you have nay idea why so?

**Comment by ghenry** [comment]
I saw this sometimes too:

https://github.com/masashi-sutou/flutter_ios_voip_kit/issues/7

Reinstalled and restarted. Maybe a sandbox issue and not as slow when on app store. Is this a live app?

**Comment by saurav0171** [comment]
No it is still in debugging mode.

**Comment by masashi-sutou** [comment]
@saurav0171 

- Please see Q&A in README.md https://github.com/masashi-sutou/flutter_ios_voip_kit#can-i-use-remote-push-device-token-instead-of-voip-device-token

**Comment by saurav0171** [comment]
@masashi-sutou 
Thanks buddy, this is what I do when it fails to fetch Voip Token
