### ISSUE TITLE
Triggering incoming call screen from voIPKit.onDidReceiveIncomingPush

### ISSUE THREAD

**Issue by ghenry** [masashi-sutou/flutter_ios_voip_kit#12]
Hi,

In https://github.com/masashi-sutou/flutter_ios_voip_kit/blob/61a93beabf2cbff32321cbab4527335459a75213/ios/Classes/SwiftFlutterIOSVoIPKitPlugin.swift#L113

i.e. `voIPKit.testIncomingCall`, we don't have to do anything like:

```
self.voIPCenter.callKitCenter.incomingCall(uuidString: uuid,
                                                   callerId: callerId,
                                                   callerName: callerName) { (error)
```

or are we triggering the native incoming call UI in `onDidReceiveIncomingPush`? My understanding is that's where I will be calling my own logic, in this case re-connecting my SIP User Agent.

Thanks.

**Comment by masashi-sutou** [comment]
- The side using the plugin does not need to call `voIPCenter.callKitCenter.incomingCall`, flutter_ios_voip_kit is calling `voIPCenter.callKitCenter.incomingCall` when receiving a VoIP notification https://github.com/masashi-sutou/flutter_ios_voip_kit/blob/master/ios/Classes/VoIPCenter.swift#L85
- The sample app calls `voIPKit.testIncomingCall` to debug the CallKit incoming screen. So I give it a test prefix.

**Comment by ghenry** [comment]
Understood, thanks.
