### ISSUE TITLE
onTokenRefresh?

### ISSUE THREAD

**Issue by ghenry** [masashi-sutou/flutter_ios_voip_kit#13]
Is there something like this like in Firebase Cloud Messaging?

**Comment by ghenry** [comment]
For example, like:

https://github.com/peerwaya/flutter_voip_push_notification/blob/master/example/lib/main.dart#L27

**Comment by masashi-sutou** [comment]
- Returns always the latest token from `getVoIPToken`.
- Make sure to call `getVoIPToken` when the app launched to update the user's VoIP device token, so I don't think it needs to be a callback to get a VoIP device token.
