### ISSUE TITLE
Clone on pub.dev

### ISSUE THREAD

**Issue by ghenry** [masashi-sutou/flutter_ios_voip_kit#16]
Any one know why this PR wasn't submitted yet, but just released on pub.dev?

https://github.com/masashi-sutou/flutter_ios_voip_kit/compare/master...tuanngotechnical:master

**Comment by masashi-sutou** [comment]
@ghenry 

Thank you for tell me issue. I replied to @tuanngotechnical on https://github.com/masashi-sutou/flutter_ios_voip_kit/issues/15#issuecomment-703955407.
