### ISSUE TITLE
How can i redirect to my application once the call is accepted at locked screen, pull-down screen?

### ISSUE THREAD

**Issue by PhuHoaJC** [masashi-sutou/flutter_ios_voip_kit#24]
My application required to video call, not audio call. Need face to face.
So i want to know. How can i redirect to my application once the call is accepted at locked screen, pull-down screen?
Is there any option for that?

**Comment by PhuHoaJC** [comment]
oh i saw the result from this issue
https://github.com/masashi-sutou/flutter_ios_voip_kit/issues/17
=((

**Comment by talwarabhimanyu** [comment]
Hi @PhuHoaJC May I ask if you were able to find a workaround? If so, I request you to kindly share. Thanks
