### ISSUE TITLE
VOIP not working when app closed (Background) in iOS 13 above

### ISSUE THREAD

**Issue by theshivamlko** [masashi-sutou/flutter_ios_voip_kit#40]
I have tried re-install app.
Your Example App is working in Foreground only not in Background( when app is closed)
I did receive some message in console but app is not invoked
I have added Background and VOIP capabilities.

My Server Code

```
var apn = require("apn");
 
  var deviceToken = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

let provider = new apn.Provider( 
    {
        token: {
            key: "AuthKey_XXXXXXXXX.p8",
            keyId: "XXXXXXXXX",
            teamId: "XXXXXXXXXXX",
            cert:"voip_services.pem"
        },
        production: false
    });

let notification = new apn.Notification();
notification.rawPayload = {
    "aps": {
        "alert": {
            "uuid": "xxxxxxxxxxxxxxxxx",
            "incoming_caller_id": "123456789",
            "incoming_caller_name": "Shivam",
        },
        "badge":2,
        'content-available': 1,
      "data": {
        "appointment_id": "47",
        "caller_name": "Shivam",
        "appointmentUUId": "22222222222222",
        "caller_id": "44",
        "type": "TO_DOCTOR",
        "click_action": "FLUTTER_NOTIFICATION_CLICK",
    },
    }
};
notification.pushType = "voip";
notification.topic = "com.xxxxx.XXXXXXXXX.voip";
notification.expiry = 0;
notification.priority = 5;

provider.send(notification, deviceToken).then((err, result) => {
    if (err) return console.log(JSON.stringify(err));
    return console.log(JSON.stringify(result))
});
```

**Comment by hovanhung98hust** [comment]
Same issue

**Comment by zionnite** [comment]
please how did you get the device token?

2) were you able to resolve the issue?

**Comment by theshivamlko** [comment]
Yes, SOLVED.  No code changes for me
- in iOS background calling works only in Release (TestFlight)
- Also device Id is different for Debug and Release mode

**Comment by zionnite** [comment]
thank you @theshivamlko for your quick response!

am still not able to wrap my head over a few things, and I will need you to help me bring clarity into it.
1) How did you make your flutter app connect to the Nodejs server, 

2) When you use this function `provider.send(notification, deviceToken)` how did you receive the payload in flutter?

3)(a) is the device token generated per User that interacts with the app or  
    (b) its device token, is just one constant string i can copy? (if yes) where can I generate it and copy it

**Comment by theshivamlko** [comment]
1. Yes, created NodeJS Code to Trigger Notification/VOIP for app. You don't need to connect NodeJS to App.  NodeJS code will send Request to Firebase(Android) and APN(iOS) resp. to trigger message in background, which invoked call notification code. Here is the nodejs code https://github.com/theshivamlko/flutter_voip_call_nodejs_android_ios
2. There is JSON format, u need to follow rules to send payload data(optional) and other values

**Comment by zionnite** [comment]
thank you @theshivamlko for all your help this far

but sir how did you get this var **deviceToken?**
`deviceToken = "e987164ba61a9afd5ckd739gnsj2305gfm48304e5798a0f7f095f7cf1ac0691";`
