### ISSUE TITLE
Error:OpenSSL SSL_read: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca, errno 0

### ISSUE THREAD

**Issue by ziasultan2** [masashi-sutou/flutter_ios_voip_kit#43]
I'm getting SSL error after using the following command you provided but it was working fine last time I used.

**Comment by http600** [comment]
I think your openssl got upgraded after your 'last time', with the latest openssl(after 3.0), you'd better run
`openssl pkcs12 -legacy -in voip_services.p12 -out voip_services.pem -nodes -clcerts`

you can check it out here:
[Legacy](https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-legacy.html) and [loading legacy PKCS#12 files that involve, for example, RC2-40-CBC, try using the -legacy option](https://www.openssl.org/docs/man3.0/man1/openssl-pkcs12.html)
