### ISSUE TITLE
In call icon guidance

### ISSUE THREAD

**Issue by ghenry** [masashi-sutou/flutter_ios_voip_kit#8]
Hi, 

At:

https://github.com/masashi-sutou/flutter_ios_voip_kit#3-add-new-image-set-for-callkit

can you provide more guidance? 

Thanks.

**Comment by masashi-sutou** [comment]
Is the following explanation insufficient?

- https://github.com/masashi-sutou/flutter_ios_voip_kit#no-icon-is-displayed-on-the-incoming-call-screen-when-locked

**Comment by ghenry** [comment]
It's a bit vague when what you include is a PDF we no exlaination how you
did it :(

**Comment by masashi-sutou** [comment]
@ghenry 

- update README.md for 0.0.4 
- https://github.com/masashi-sutou/flutter_ios_voip_kit#no-icon-is-displayed-on-the-incoming-call-screen-when-locked

**Comment by ghenry** [comment]
Perfect! Really nice touch. Thanks for this.
